package irrgarten.UI;
import irrgarten.Directions;
import irrgarten.GameState;
/**
 *
 * @author usuario
 */
public class GraphicUI extends javax.swing.JFrame implements UI{
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GraphicUI.class.getName());
    private Cursors cursor;

    /**
     * Creates new form GraphicUI
     */
    public GraphicUI() {
        cursor = new Cursors(this,true);
        initComponents();
        setVisible(true);
    }
    
    @Override
    public Directions nextMove(){
        return cursor.getDirection();
    }

    @Override
    public void showGame(GameState gameState){
        LaberintoTexto.setText(gameState.getLabyrinth());
        Jugadores.setText(gameState.getPlayers());
        Monstruos.setText(gameState.getMonsters());
        Log.setText(gameState.getLog());
        Turno.setText("Turno del jugador: " + gameState.getCurrentPlayer());
        
        if (gameState.getWinner()) {
            Ganador.setText("El jugador " + gameState.getCurrentPlayer()
                + " ha ganado la partida.");
        }
        else {
            Ganador.setText("Sin ganador");
        }
        this.repaint();
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        LaberintoTexto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Log = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Jugadores = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        Monstruos = new javax.swing.JTextArea();
        Turno = new javax.swing.JLabel();
        Ganador = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LaberintoTexto.setColumns(20);
        LaberintoTexto.setFont(new java.awt.Font("Courier", 0, 15)); // NOI18N
        LaberintoTexto.setRows(5);
        jScrollPane1.setViewportView(LaberintoTexto);

        Log.setColumns(20);
        Log.setRows(5);
        jScrollPane2.setViewportView(Log);

        Jugadores.setColumns(20);
        Jugadores.setRows(5);
        jScrollPane3.setViewportView(Jugadores);

        Monstruos.setColumns(20);
        Monstruos.setRows(5);
        jScrollPane5.setViewportView(Monstruos);

        Turno.setText("Turno");

        Ganador.setText("Ganador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Turno)
                                    .addComponent(Ganador))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(Turno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ganador)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ganador;
    private javax.swing.JTextArea Jugadores;
    private javax.swing.JTextArea LaberintoTexto;
    private javax.swing.JTextArea Log;
    private javax.swing.JTextArea Monstruos;
    private javax.swing.JLabel Turno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
